apiVersion: v1
kind: Service
metadata:
  name: gateway-proxy
  namespace: sentinel-gateway
  annotations:
    # Public-facing NLB provisioned in the public subnets tagged kubernetes.io/role/elb=1
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: gateway-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
